#!/bin/bash

function tm3x3() {
	[ -z "${TMUX}" ] && tmux new-session -d "3x3"
	tmux split-window -h
	tmux split-window -h
	tmux select-layout even-horizontal
	tmux split-window -v
	tmux select-pane -L
	tmux split-window -v
	tmux select-pane -L
	tmux split-window -v
	tmux select-pane -U
	tmux select-pane -R
	[ -z "${TMUX}" ] && tmux -2 attach-session -d 
}


