call IMAP ('CC', '\mathbb{C} ', 'tex')
call IMAP (g:Tex_Leader.'|', '\Big| <++> \Big|<++>', 'tex')
call IMAP (g:Tex_Leader.'P', '\langle <++>, <++> \rangle <++>', 'tex')
call IMAP (g:Tex_Leader.'u', "u_{<++>}^{<++>}<++>", 'tex')
call IMAP ('<<', '\langle <++> \rangle <++> ', 'tex')
call IMAP ('||', '\left| <++> \right| <++>', 'tex')
call IMAP ('NN', '\mathbb{N} ', 'tex')
call IMAP ('QQ', '\mathbb{Q} ', 'tex')
call IMAP ('RR', '\mathbb{R} ', 'tex')
call IMAP ('ZZ', '\mathbb{Z} ', 'tex')
