#!/bin/bash

if [ -n "${TMUX}" ]; then
	if [ "${COLUMNS}" -lt 160 ] || [ "${LINES}" -lt 50 ]; then
		echo "Not enough COLUMNS (need bigger than 160)"
	else
		[ -z "${TMUX}" ] && tmux new-session -d "2x3"
		tmux split-window -h
		tmux select-pane -L
		tmux resize-pane -x 80
		tmux split-window -v
		tmux select-pane -R
		[ -z "${TMUX}" ] && tmux -2 attach-session -d 
	fi
else
	echo "TMUX not running"
fi
