#!/bin/bash

PTOS=( 12 14 16 18 20 22 24 28 32 )
for pt in ${PTOS[*]}; do
	echo $pt
	grub-mkfont -s ${pt} -o /boot/grub/TerminusBold_${pt}.pf2 /home/igormorgado/Downloads/terminus-ttf-4.46.0/TerminusTTF-Bold-4.46.0.ttf
	grub-mkfont -s ${pt} -o /boot/grub/TerminusRegular_${pt}.pf2 /home/igormorgado/Downloads/terminus-ttf-4.46.0/TerminusTTF-4.46.0.ttf
done
