#!/usr/bin/bash
# Python stuff

PYTHONSTARTUP=~/.pythonrc.py
[ -r "${PYTHONSTARTUP}" ] && export PYTHONSTARTUP

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
addpath "${HOME}/.pyenv/bin"


if which pyenv; then
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
	pyenv  activate venv36
fi

## For python virtualenv 
#VIRTUALENV_DIR=${HOME}/venv/
#if [ -r "${VIRTUALENV_DIR}/bin/activate" ]; then
#    source "${VIRTUALENV_DIR}/bin/activate"
#fi

# vim: ft=sh:
