#!/bin/bash
# shellcheck  disable=SC1090
# shellcheck  disable=SC1091
# shellcheck  disable=SC2154

# If not running interactively, don't do anything
case $- in
	*i*) ;;
	*) return ;;
esac

# We are running interactively. Let's start to setup environment.

# Preload {{{
######################################################################

# How many colors on terminal? Colorize!

#COLORS
if [ "$(tput colors)" -gt 0 ] ; then
	  BLACK=$(tput setaf 0)
	    RED=$(tput setaf 1)
	  GREEN=$(tput setaf 2)
	  BROWN=$(tput setaf 3)
	   BLUE=$(tput setaf 4)
	 PURPLE=$(tput setaf 5)
	   CYAN=$(tput setaf 6)
	  LGRAY=$(tput setaf 7)
	  DGRAY=$(tput setaf 8)
	   LRED=$(tput setaf 9)
	 LGREEN=$(tput setaf 10)
	 YELLOW=$(tput setaf 11)
	  LBLUE=$(tput setaf 12)
	LPURPLE=$(tput setaf 13)
	  LCYAN=$(tput setaf 14)
	  WHITE=$(tput setaf 15)
	 BBLACK=$(tput setab 0)
	   BRED=$(tput setab 1)
	 BGREEN=$(tput setab 2)
	 BBROWN=$(tput setab 3)
	  BBLUE=$(tput setab 4)
	BPURPLE=$(tput setab 5)
	  BCYAN=$(tput setab 6)
	 BLGRAY=$(tput setab 7)
	 BDGRAY=$(tput setab 8)
	  BLRED=$(tput setab 9)
	BLGREEN=$(tput setab 10)
	BYELLOW=$(tput setab 11)
	 BLBLUE=$(tput setab 12)
   BLPURPLE=$(tput setab 13)
	 BLCYAN=$(tput setab 14)
	 BWHITE=$(tput setab 15)
       BOLD=$(tput bold)
	    DIM=$(tput dim)
     ITALIC="\e[3m"
	  UNDER=$(tput smul)
     STRIKE="\e[9m"
     	REV=$(tput rev)
	  BLINK=$(tput blink)
	NOUNDER=$(tput rmul)
	   CRST=$(tput sgr0 )
	    RST=$(tput op)
	  
	export BOLD DIM ITALIC UNDER STRIKE REV BLINK NOUNDER CRST RST
	export BLACK RED GREEN BROWN BLUE PURPLE CYAN LGRAY 
	export DGRAY LRED LGREEN YELLOW LBLUE LPURPLE LCYAN WHITE 
	export BBLACK BRED BGREEN BBROWN BBLUE BPURPLE BCYAN BLGRAY 
	export BDGRAY BLRED BLGREEN BYELLOW BLBLUE BLPURPLE BLCYAN BWHITE 
fi


[ -f "/etc/profile.d/vte-2.91.sh" ] && source /etc/profile.d/vte-2.91.sh

# Run all files to 99 on ~/.bashrc.d/
for file in ${HOME}/.bashrc.d/0*;do
	source "${file}"
done
# }}}

# Terminal independant settings {{{
###########################################################################

# Add paths
addpath "${HOME}"/bin
addpath "${HOME}"/usr/bin
addpath "${HOME}"/.local/bin
addpath /Applications/MacVim.app/Contents/MacOS/
addpath "/c/Anaconda"
addpath "/c/Anaconda2"
addpath "/c/Anaconda3"

# Disable logouts
export TMOUT=

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
export HISTCONTROL=ignorespace:erasedups
export HISTSIZE=100000
export HISTFILESIZE=3000000
export HISTTIMEFORMAT="%F %T : "
export HISTIGNORE="[fb]g:exit:ls:history:?:??:pwd"

# append to the history file, don't overwrite it
shopt -s histappend

# Multilines together
shopt -s cmdhist

# One day I will return to vim mode
set -o vi
#set editing-mode vi
#set keymap vi-command

# Enable notifications of running jobs
set -o notify

# Case insesitive filename globbing
shopt -s nocaseglob

# Fix small tipos on CDs
shopt -s cdspell

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot}" ] && [ -r /etc/debian_chroot ]; then
	debian_chroot=$(cat /etc/debian_chroot)
fi

stty stop undef # to unmap ctrl-s

#}}}

# Applications configuration {{{
######################################################################

export EDITOR="vim"
export GIT_EDITOR="vim"

# Configure nmon
export NMON=vcmknt.

# CVS Sample
CVS_RSH=ssh
CVSROOT=:ext:imorgado@HOSTNAME:/PATH
export CVS_RSH CVSROOT

# MC settings
export MC_SKIN=$HOME/.config/mc/solarized.ini

#}}}

# Terminal Configuration {{{
###########################################################################

# For now just set as tru
COLOR_ENVIRONMENT=true

# Evaluating boot command line
kernel_color_theme
export BACKGROUND COLOR

# dircolors... make sure that we have a color terminal, dircolors exists, and
# ls supports it.
[ -f "${HOME}/.dir_colors" ] && source <(dircolors -b "${HOME}/.dir_colors") 

# Load Xprofile
[ -r "${HOME}/.xprofile" ] && [ -n "${DISPLAY}" ] && source "${HOME}/.xprofile" 

#}}}

# Terminal dependant settings {{{
###########################################################################


###############
### PS1
###############

# Colorize term (no exceptions for now)
if ${COLOR_ENVIRONMENT}; then
	PS1="${debian_chroot:+($debian_chroot)}\[${BLUE}\]\u\[${GREEN}\]@\[${BLUE}\]\h\[${CRST}\]:\[${RED}\]\w\[${CRST}\] ( \$(lsbytesum) )\n"
else
	PS1="${debian_chroot:+($debian_chroot)}\u\@\h:\w ( \$(lsbytesum) )\n"
fi

# Add git and svn branch names
[ -x "$(which git)" ] && PS1="$PS1\$(parse_git_branch)"
[ -x "$(which svn)" ] && PS1="$PS1\$(parse_svn_branch)"


# Add last status and colorize
if ${COLOR_ENVIRONMENT}; then
	PS1="${PS1}\[\$prevCmd\]\$\[$CRST\] "
else
	PS1="${PS1}\$ "
fi

PROMPT_COMMAND=bash_prompt_command
export PROMPT_COMMAND

export PS4='+($?) $BASH_SOURCE:$FUNCNAME:$LINENO:'

# }}}

# Final configurations {{{
######################################################################

addpkgpath "${HOME}"/usr/lib/pkgconfig
addlibpath "${HOME}"/usr/lib
addrunpath "${HOME}"/usr/lib

addpkgpath "${HOME}"/.local/lib/pkgconfig
addlibpath "${HOME}"/.local/lib
addrunpath "${HOME}"/.local/lib

addpkgpath "${HOME}"/lib/pkgconfig
addlibpath "${HOME}"/lib
addrunpath "${HOME}"/lib

addmanpath "${HOME}/.local/man"
addinfopath "${HOME}/.local/info"

addxdgdatadir "/var/lib/flatpak/exports/share/applications"

# Load some external files
loadresource ~/.local/bin/factory
loadresource ~/.bash_aliases
loadresource ~/.bash_python
loadresource ~/.bash_tmux
loadresource ~/.bash_nda
loadresource ~/.bash_seismic


PS1="\n${PS1}"
export PS1

# Bash completion
[ ! "$(shopt -oq posix)" ] && loadresource /etc/bash_completion
export COMP_CVS_REMOTE=1
export COMP_CONFIGURE_HINTS=1
export COMP_TAR_INTERNAL_PATHS=1

#}}}

# Overload default utilities {{{
######################################################################

if [ -x "$(which pinfo)" ]; then
	alias man='pinfo -m'
fi

# }}}


# Run all files greater than 99 on ~/.bashrc.d/
for file in ${HOME}/.bashrc.d/[123456789]*;do
	source "${file}"
done
unset file

# vim: foldmethod=marker:ft=sh:

